export const kanbanDetails = {
  id: 83,
  name: "ENG",
  area_id: 12,
  columns: 5,
  rows: 4,
};
export const slotData = [
  {
    slot_coord: "5,1",
    itemid: "00065",
    req_capacity: 2,
    balance: 0,
    slot_id: 10855,
  },
  {
    slot_coord: "3,1",
    itemid: "00033",
    req_capacity: 1,
    balance: 0,
    slot_id: 10854,
  },
  {
    slot_coord: "1,2",
    itemid: "00018",
    req_capacity: 3,
    balance: 0,
    slot_id: 10853,
  },
  {
    slot_coord: "1,1",
    itemid: "111qa",
    req_capacity: 1,
    balance: 0,
    slot_id: 10857,
  },
  {
    slot_coord: "2,1",
    itemid: "00024",
    req_capacity: 1,
    balance: 0,
    slot_id: 10856,
  },
  {
    slot_coord: "2,2",
    itemid: "00032",
    req_capacity: 1,
    balance: 0,
    slot_id: 10858,
  },
  {
    slot_coord: "3,2",
    itemid: "00098",
    req_capacity: 3,
    balance: 0,
    slot_id: 10859,
  },
  {
    slot_coord: "4,2",
    itemid: "00100",
    req_capacity: 2,
    balance: 0,
    slot_id: 10860,
  },
  {
    slot_coord: "4,1",
    itemid: "00045",
    req_capacity: 8,
    balance: 0,
    slot_id: 10861,
  },
  {
    slot_coord: "4,3",
    itemid: "00122",
    req_capacity: 35,
    balance: 0,
    slot_id: 10862,
  },
  {
    slot_coord: "5,2",
    itemid: "00104",
    req_capacity: 2,
    balance: 0,
    slot_id: 10866,
  },
  {
    slot_coord: "2,3",
    itemid: "00105",
    req_capacity: 2,
    balance: 0,
    slot_id: 10865,
  },
  {
    slot_coord: "5,3",
    itemid: "38939",
    req_capacity: 1,
    balance: 0,
    slot_id: 10864,
  },
  {
    slot_coord: "3,3",
    itemid: "00117",
    req_capacity: 2,
    balance: 0,
    slot_id: 10867,
  },
  {
    slot_coord: "1,3",
    itemid: "00101",
    req_capacity: 3,
    balance: 0,
    slot_id: 10863,
  },
  {
    slot_coord: "1,4",
    itemid: "00194",
    req_capacity: 1,
    balance: 0,
    slot_id: 10868,
  },
  {
    slot_coord: "2,4",
    itemid: null,
    req_capacity: null,
    balance: 0,
    slot_id: 10870,
  },
  {
    slot_coord: "5,4",
    itemid: null,
    req_capacity: null,
    balance: 0,
    slot_id: 10869,
  },
  {
    slot_coord: "3,4",
    itemid: null,
    req_capacity: null,
    balance: 0,
    slot_id: 10872,
  },
  {
    slot_coord: "4,4",
    itemid: null,
    req_capacity: null,
    balance: 0,
    slot_id: 10871,
  },
  {
    slot_coord: "2,5",
    itemid: null,
    req_capacity: null,
    balance: 0,
    slot_id: 10873,
  },
  {
    slot_coord: "4,5",
    itemid: null,
    req_capacity: null,
    balance: 0,
    slot_id: 10875,
  },
  {
    slot_coord: "1,5",
    itemid: null,
    req_capacity: null,
    balance: 0,
    slot_id: 10876,
  },
  {
    slot_coord: "3,5",
    itemid: null,
    req_capacity: null,
    balance: 0,
    slot_id: 10874,
  },
  {
    slot_coord: "5,5",
    itemid: null,
    req_capacity: null,
    balance: 0,
    slot_id: 10877,
  },
  {
    slot_coord: "3,6",
    itemid: null,
    req_capacity: null,
    balance: 0,
    slot_id: 10878,
  },
  {
    slot_coord: "4,6",
    itemid: null,
    req_capacity: null,
    balance: 0,
    slot_id: 10879,
  },
  {
    slot_coord: "2,6",
    itemid: null,
    req_capacity: null,
    balance: 0,
    slot_id: 10881,
  },
  {
    slot_coord: "1,6",
    itemid: null,
    req_capacity: null,
    balance: 0,
    slot_id: 10880,
  },
  {
    slot_coord: "5,6",
    itemid: null,
    req_capacity: null,
    balance: 0,
    slot_id: 10882,
  },
];
